server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mytest?useSSL=false&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#邮件服务
mail:
  host: smtp.163.com
  account: 18939206470@163.com
  pwd: MPEVSEJBRRVEAUOV
  debug: true
  port: 25