server:
  port: 8084

spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300 #格式 ip:端口 多个节点逗号隔开
      cluster-name: my-application
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mytest?useSSL=false&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl